# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

name: eg3d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python = 3.12
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch>=2.1.0
  - cudatoolkit>=11.1
  - requests>=2.26.0
  - tqdm>=4.62.2
  - ninja>=1.10.2
  - matplotlib>=3.4.2
  - imageio>=2.9.0
  - psutil
  - tensorboard
  - mrcfile
  - pyglfw>=2.2.0
  - glfw
  - imageio-ffmpeg>=0.4.3
  - pip:
      - pyopengl>=3.1.5
      - imgui>=1.3.0
      - pyspng